return {
	"simrat39/symbols-outline.nvim",
	enabled = false,
	event = "VeryLazy",
	config = function()
		require("symbols-outline").setup({
			highlight_hovered_item = false,
			show_guides = true,
			auto_preview = false,
			position = "right",
			relative_width = true,
			width = 30,
			auto_close = false,
			show_numbers = false,
			show_relative_numbers = true,
			show_symbol_details = true,
			preview_bg_highlight = "Pmenu",
			autofold_depth = nil,
			auto_unfold_hover = true,
			fold_markers = { "", "" },
			wrap = false,
			keymaps = {
				close = { "<Esc>", "q" },
				goto_location = "<Cr>",
				focus_location = "f",
				hover_symbol = "K",
				toggle_preview = "t",
				rename_symbol = "r",
				code_actions = "a",
				fold = "h",
				unfold = "l",
				fold_all = "H",
				unfold_all = "L",
				fold_reset = "R",
			},
			lsp_blacklist = {},
			symbol_blacklist = {},
			symbols = {
				File = { icon = "", hl = "@text.uri" },
				Module = { icon = "", hl = "@namespace" },
				Namespace = { icon = "", hl = "@namespace" },
				Package = { icon = "", hl = "@namespace" },
				Class = { icon = "𝓒", hl = "@type" },
				Method = { icon = "ƒ", hl = "@method" },
				Property = { icon = "", hl = "@method" },
				Field = { icon = "", hl = "@field" },
				Constructor = { icon = "", hl = "@constructor" },
				Enum = { icon = "ℰ", hl = "@type" },
				Interface = { icon = "ﰮ", hl = "@type" },
				Function = { icon = "", hl = "@function" },
				Variable = { icon = "", hl = "@constant" },
				Constant = { icon = "", hl = "@constant" },
				String = { icon = "𝓐", hl = "@string" },
				Number = { icon = "#", hl = "@number" },
				Boolean = { icon = "⊨", hl = "@boolean" },
				Array = { icon = "", hl = "@constant" },
				Object = { icon = "⦿", hl = "@type" },
				Key = { icon = "🔐", hl = "@type" },
				Null = { icon = "NULL", hl = "@type" },
				EnumMember = { icon = "", hl = "@field" },
				Struct = { icon = "𝓢", hl = "@type" },
				Event = { icon = "🗲", hl = "@type" },
				Operator = { icon = "+", hl = "@operator" },
				TypeParameter = { icon = "𝙏", hl = "@parameter" },
				Component = { icon = "", hl = "@function" },
				Fragment = { icon = "", hl = "@constant" },
			},
		})

		local keymap = vim.keymap
		keymap.set("n", "<leader>ss", "<cmd> SymbolsOutline <cr>", { desc = "Open symbol oultine window" })
		keymap.set("n", "<leader>sc", "<cmd> SymbolsOutlineClose <cr>", { desc = "Close symbol oultine window" })
	end,
}
